name: Tests

on: [push, pull_request]

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
        matrix:
          include:
          - php-version: 8.0.*
            symfony-version: 6.0.*
          - php-version: 8.0
            symfony-version: 5.0.*
          - php-version: 8.0
            symfony-version: 4.4.*
          - php-version: 7.4
            symfony-version: 5.0.*
          - php-version: 7.4
            symfony-version: 4.4.*
          - php-version: 7.4
            symfony-version: 4.3.*
          - php-version: 7.3
            symfony-version: 5.0.*
          - php-version: 7.3
            symfony-version: 4.4.*
          - php-version: 7.3
            symfony-version: 4.3.*
          - php-version: 7.2
            symfony-version: 4.2.*
          - php-version: 7.1
            symfony-version: 3.4.*
          - php-version: 7.1
            symfony-version: 2.8.*
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
           php-version: ${{ matrix.php-version }}
           ini-values: phar.readonly=0
    - name: Git config email
      run: git config --global user.email "test@test.com"
    - name: Git config name
      run: git config --global user.name "John Doe"
    - name: Install Dependencies
      run: |
        composer self-update
        composer require "symfony/console:${{ matrix.symfony-version }}" "symfony/yaml:${{ matrix.symfony-version }}" "symfony/process:${{ matrix.symfony-version }}" --no-update;
        composer update --prefer-dist
        composer require "phpunit/phpunit" --dev
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: bin/phpunit
